[package]
name = "sailtrack-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24"
eskf = "0.2.0"
nalgebra = "=0.25.4"
quaternion-core = "0.5.0"
tokio = { version = "1.17.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.116"