[package]
name = "sailtrack-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24"
eskf = "0.2"
nalgebra = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
