services:
  dockerpi:
    build:
      context: https://github.com/matteocarnelos/dockerpi.git
      target: dockerpi-vm
    image: lukechilds/dockerpi:vm
    volumes:
      - ./filesystem.img:/sdcard/filesystem.img
    ports:
      - "22:22"       # SSH
      - "1883:1883"   # MQTT
    environment:
      - HOSTFWD=tcp::22-:22 tcp::1883-:1883
    sysctls:
      - net.ipv4.ping_group_range=0 2147483647
