[tasks.default]
clear = true
dependencies = [
    "check-format",
    "clippy",
    "build-release",
]

[tasks.build-release]
command = "cross"

[tasks.package]
clear = true
condition = { platforms = [ "linux" ] }
dependencies = ["default"]
command = "sudo"
args = ["./.make/sailtrack-package"]

[tasks.upload]
dependencies = ["default"]
script = '''
scp sailtrack/sailtrack-* target/aarch64-unknown-linux-gnu/release/sailtrack-*[!.d] \
root@${1-192.168.42.1}:/boot/sailtrack
'''
