#!/bin/bash

# Set variables
debian_release_name="Bookworm"
dietpi_image_name="DietPi_RPi-ARMv8-$debian_release_name"
sailtrack_image_name="SailTrack-Core_RPi-ARMv8-$debian_release_name"

# Download and extract image
wget -N "https://dietpi.com/downloads/images/$dietpi_image_name.7z" -P /tmp/sailtrack-build || exit 1
7z e -aoa -o"/tmp/sailtrack-build/$dietpi_image_name" "/tmp/sailtrack-build/$dietpi_image_name.7z"

# Mount image
fp_loop=$(losetup --show -fP "/tmp/sailtrack-build/$dietpi_image_name/$dietpi_image_name.img")
mkdir -p /tmp/sailtrack-build/mnt
mount "${fp_loop}p2" /tmp/sailtrack-build/mnt
mount "${fp_loop}p1" /tmp/sailtrack-build/mnt/boot

# Copy files
cp -v LICENSE /tmp/sailtrack-build/mnt/boot/sailtrack-LICENSE.txt
cp -v README.md /tmp/sailtrack-build/mnt/boot/sailtrack-README.md
cp -v dietpi.txt /tmp/sailtrack-build/mnt/boot/dietpi.txt
cp -v Automation_Custom_Script.sh /tmp/sailtrack-build/mnt/boot/Automation_Custom_Script.sh
cp -vr sailtrack /tmp/sailtrack-build/mnt/boot/sailtrack
cp -vrT rootfs /tmp/sailtrack-build/mnt

# Unmount image
umount -R /tmp/sailtrack-build/mnt
losetup -d "$fp_loop"

# Rename image
mv "/tmp/sailtrack-build/$dietpi_image_name/$dietpi_image_name.img" "/tmp/sailtrack-build/$dietpi_image_name/$sailtrack_image_name.img"

# Update hashes
echo -n "Generating hashes..."
cat << EOF > "/tmp/sailtrack-build/$dietpi_image_name/hash.txt"
FILE:   $sailtrack_image_name.img
DATE:   $(date -u)
MD5:    $(md5sum "/tmp/sailtrack-build/$dietpi_image_name/$sailtrack_image_name.img" | mawk '{print $1}')
SHA1:   $(sha1sum "/tmp/sailtrack-build/$dietpi_image_name/$sailtrack_image_name.img" | mawk '{print $1}')
SHA256: $(sha256sum "/tmp/sailtrack-build/$dietpi_image_name/$sailtrack_image_name.img" | mawk '{print $1}')
EOF
echo "done"

# Update README
cp -v README.md "/tmp/sailtrack-build/$dietpi_image_name"

# Create archive
(( $(free -m | mawk '/Mem:/{print $2}') < 1750 && $(nproc) > 2 )) && limit_threads='-mmt2'
7z a -m0=lzma2 -mx=9 $limit_threads "$sailtrack_image_name.7z" "/tmp/sailtrack-build/$dietpi_image_name/*"
