#!/bin/bash

# Check arguments
if [ -z "$1" ]; then
  echo "sailtrack-build: missing argument: DIETPI_IMG_NAME"
  echo "Usage: sailtrack-build DIETPI_IMG_NAME OUTPUT_IMG_NAME"
  exit 1
fi

if [ -z "$2" ]; then
  echo "sailtrack-build: missing argument: OUTPUT_IMG_NAME"
  echo "Usage: sailtrack-build DIETPI_IMG_NAME OUTPUT_IMG_NAME"
  exit 1
fi

# Set variables
DIETPI_IMG_NAME=$1
OUTPUT_IMG_NAME=$2

# Download and extract image
wget -N "https://dietpi.com/downloads/images/$DIETPI_IMG_NAME.7z" -P /tmp/sailtrack-build || exit 1
7z e -aoa -o"/tmp/sailtrack-build/$DIETPI_IMG_NAME" "/tmp/sailtrack-build/$DIETPI_IMG_NAME.7z"

# Mount image
FP_LOOP=$(losetup --show -f -P "/tmp/sailtrack-build/$DIETPI_IMG_NAME/$DIETPI_IMG_NAME.img")
mkdir /tmp/sailtrack-build/mnt
mount "${FP_LOOP}p2" /tmp/sailtrack-build/mnt
mount "${FP_LOOP}p1" /tmp/sailtrack-build/mnt/boot

# Copy files
cp -v LICENSE /tmp/sailtrack-build/mnt/boot/sailtrack-LICENSE.txt
cp -v README.md /tmp/sailtrack-build/mnt/boot/sailtrack-README.md
cp -v dietpi.txt /tmp/sailtrack-build/mnt/boot/dietpi.txt
cp -v Automation_Custom_Script.sh /tmp/sailtrack-build/mnt/boot/Automation_Custom_Script.sh
cp -vr sailtrack /tmp/sailtrack-build/mnt/boot/sailtrack
cp -vrT rootfs /tmp/sailtrack-build/mnt

# Unmount image
umount -R /tmp/sailtrack-build/mnt
losetup -d "$FP_LOOP"

# Rename image
mv "/tmp/sailtrack-build/$DIETPI_IMG_NAME/$DIETPI_IMG_NAME.img" "/tmp/sailtrack-build/$DIETPI_IMG_NAME/$OUTPUT_IMG_NAME.img"

# Update hashes
echo -n "Generating hashes..."
cat << _EOF_ > "/tmp/sailtrack-build/$DIETPI_IMG_NAME/hash.txt"
FILE:   $OUTPUT_IMG_NAME.img
DATE:   $(date -u)
MD5:    $(md5sum "/tmp/sailtrack-build/$DIETPI_IMG_NAME/$OUTPUT_IMG_NAME.img" | mawk '{print $1}')
SHA1:   $(sha1sum "/tmp/sailtrack-build/$DIETPI_IMG_NAME/$OUTPUT_IMG_NAME.img" | mawk '{print $1}')
SHA256: $(sha256sum "/tmp/sailtrack-build/$DIETPI_IMG_NAME/$OUTPUT_IMG_NAME.img" | mawk '{print $1}')
_EOF_
echo "done"

# Update README
cp -v README.md "/tmp/sailtrack-build/$DIETPI_IMG_NAME"

# Create archive
(( $(free -m | mawk '/Mem:/{print $2}') < 1750 && $(nproc) > 2 )) && limit_threads='-mmt2'
7z a -m0=lzma2 -mx=9 $limit_threads "$OUTPUT_IMG_NAME.7z" "/tmp/sailtrack-build/$DIETPI_IMG_NAME/*"
