#!/bin/bash

# `sailtrack-x708_softsd` - Shell script that powers off the Raspberry Pi by 
# sending an impulse to the Geekworm X708 power HAT. This is required in order 
# to perform a full software shutdown (softwarecshutdown + battery power 
# disconnected). Otherwise, you will only be able to perform a software 
# shutdown.

if [ "$EUID" -ne 0 ]
  then echo "poweroff: permission denied"
  exit
fi

BUTTON_PIN=13
SLEEP_TIME_SEC=4

echo $BUTTON_PIN > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio$BUTTON_PIN/direction

echo "1" > /sys/class/gpio/gpio$BUTTON_PIN/value
/bin/sleep $SLEEP_TIME_SEC
echo "0" > /sys/class/gpio/gpio$BUTTON_PIN/value
