name: Build image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIETPI_IMAGE_NAME: DietPi_RPi-ARMv6-Buster
      OUTPUT_IMAGE_NAME: SailTrack_Core-ARMv6-Buster
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: sailtrack-core

      - name: Download compressed image
        run: wget https://dietpi.com/downloads/images/$DIETPI_IMAGE_NAME.7z

      - name: Extract image
        run: |
          7z e -o$DIETPI_IMAGE_NAME $DIETPI_IMAGE_NAME.7z
          mv ${DIETPI_IMAGE_NAME}/${DIETPI_IMAGE_NAME}.img ${DIETPI_IMAGE_NAME}/${OUTPUT_IMAGE_NAME}.img

      - name: Mount image
        run: |
          DEV=$(sudo losetup --show -f -P $DIETPI_IMAGE_NAME/$OUTPUT_IMAGE_NAME.img)
          PART=${DEV}p1
          MOUNT=/mnt/$(basename $PART)
          echo "DEV=$DEV" >> $GITHUB_ENV
          echo "PART=$PART" >> $GITHUB_ENV
          echo "MOUNT=$MOUNT" >> $GITHUB_ENV
          sudo mkdir $MOUNT
          sudo mount $PART $MOUNT

      - name: Copy files and directories
        run: |
          mv sailtrack-core/LICENSE sailtrack-core/sailtrack-LICENSE.txt
          mv sailtrack-core/README.md sailtrack-core/sailtrack-README.md
          sudo rsync -rt --exclude=".*" sailtrack-core/ $MOUNT

      - name: Unmount image
        run: |
          sudo umount $MOUNT
          sudo losetup -d $DEV

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.DIETPI_IMAGE_NAME }}/${{ env.OUTPUT_IMAGE_NAME }}.img
          name: ${{ env.OUTPUT_IMAGE_NAME }}
