name: Build Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SailTrack-Build
        run: sudo ./.build/sailtrack-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SailTrack-Core_RPi-ARMv8-Bookworm.7z
          path: SailTrack-Core_RPi-ARMv8-Bookworm.7z
          compression-level: 0
