name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SailTrack-Build
        run: sudo ./.build/sailtrack-build

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: SailTrack-Core_RPi-ARMv8-Bookworm.7z
          generate_release_notes: true
